FROM apache/airflow:3.1.7-python3.12

USER root

RUN apt-get update && \
    apt-get install -y \
    pkg-config \
    default-libmysqlclient-dev \
    build-essential

USER airflow

RUN pip install \
    apache-airflow-providers-mysql \
    apache-airflow-providers-postgres \
    pandas==2.3.3 \
    sqlalchemy==2.0.46 \
    pymysql==1.1.2
